# backend/postgres-seed/docker-compose.yml
version: "3.9"

services:
  postgres-seed:
    build:
      context: ..
      dockerfile: postgres-seed/Dockerfile
    hostname: postgres-seed
    container_name: postgres-seed
    depends_on:
      - db_postgres
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ${SRC_PATH}:/home/app/src
      - ${DATA_PATH}:/path/in/container:rw

  db_postgres:
    container_name: postgres
    build:
      context: ./db
      dockerfile: Dockerfile
      
    hostname: db_postgres
    restart: on-failure
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - db-postgres:/var/lib/postgresql/data
      - ${DATA_PATH}:/path/in/container
    

  pg-admin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@email.com
      - PGADMIN_DEFAULT_PASSWORD=admin
      - PGADMIN_LISTEN_PORT=5050

    ports:
      - "5050:5050"

volumes:
  db-postgres:
    driver: local
