version: "3.9"

services:
  raw_data:
    build:
      context: .
      dockerfile: raw_data/Dockerfile
    hostname: raw_data
    container_name: raw_data
    depends_on:
      - db_postgres
    ports:
      - "8000:8000"
    networks:
      default:
        aliases:
          - raw_data.dev

  risk:
    build:
      context: .
      dockerfile: risk/Dockerfile
    hostname: risk
    container_name: risk
    depends_on:
      - db_postgres
    ports:
      - "8001:8000"
    networks:
      default:
        aliases:
          - risk.dev

  data_management:
    build:
      context: .
      dockerfile: data_management/Dockerfile
    hostname: data_management
    container_name: data_management
    depends_on:
      - db_postgres
    ports:
      - "8002:8000"
    networks:
      default:
        aliases:
          - data_management.dev

  db_postgres:
    image: postgres:latest
    container_name: postgres
    hostname: db_postgres
    restart: on-failure
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=grayfox_db
    ports:
      - "5432:5432"
    volumes:
      - db-postgres:/var/lib/postgresql/data
    networks:
      default:
        aliases:
          - db_postgres.dev

  pg-admin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@email.com
      - PGADMIN_DEFAULT_PASSWORD=admin
      - PGADMIN_LISTEN_PORT=5050
    ports:
      - "5050:5050"
    networks:
      default:
        aliases:
          - pgadmin.dev

volumes:
  db-postgres:
    driver: local

networks:
  default:
    name: grayfox_network
    driver: bridge
