version: "3.9"

services:
  data_management:
    build:
      context: .
      dockerfile: data_management/Dockerfile
    hostname: data_management
    container_name: data_management
    depends_on:
      - db_postgres
    ports:
      - "8000:8000"
    env_file:
      - .env  # Adjusted path to the .env file
    volumes:
      - ./data_management/src:/home/app/src
      - ./data_management/data:/home/app/data:rw

  db_postgres:
    image: postgres:15.3
    container_name: postgres
    hostname: db_postgres
    restart: on-failure
    env_file:
      - .env  # Adjusted path to the .env file
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - db-postgres:/var/lib/postgresql/data
      - ./data_management/data:/home/app/data

  pg-admin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@email.com
      - PGADMIN_DEFAULT_PASSWORD=admin
      - PGADMIN_LISTEN_PORT=5050
    ports:
      - "5050:5050"

volumes:
  db-postgres:
    driver: local
