version: "3.9"

services:
  seeder:
    build:
      context: .
      dockerfile: seeder/Dockerfile
    hostname: seeder
    container_name: seeder
    depends_on:
      - db_postgres
    ports:
      - "7999:8000"
    volumes:
      - ./seeder/src:/home/app/src
      - ./common:/home/app/common
      - ./risk:/home/app/risk
      - ./raw_data:/home/app/raw_data
      - /home/patrik/repos/pysystemtrade_preprocessing/data:/path/in/container:rw

  raw_data:
    build:
      context: .
      dockerfile: raw_data/Dockerfile
    hostname: raw_data
    container_name: raw_data
    depends_on:
      - db_postgres
    ports:
      - "8000:8000"
    volumes:
      - ./raw_data/src:/home/app/src
      - ./common:/home/app/common


  risk:
    build:
      context: .
      dockerfile: risk/Dockerfile
    hostname: risk
    container_name: risk
    depends_on:
      - db_postgres
    ports:
      - "8001:8000"
    volumes:
      - ./risk/src:/home/app/src
      - ./common:/home/app/common

  data_management:
    build:
      context: .
      dockerfile: data_management/Dockerfile
    hostname: data_management
    container_name: data_management
    depends_on:
      - db_postgres
    ports:
      - "8002:8000"
    volumes:
      - ./data_management/src:/home/app/src

  db_postgres:
    image: postgres:latest
    container_name: postgres
    hostname: db_postgres
    restart: on-failure
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=grayfox_db
    ports:
      - "5432:5432"
    volumes:
      - db-postgres:/var/lib/postgresql/data

  pg-admin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@email.com
      - PGADMIN_DEFAULT_PASSWORD=admin
      - PGADMIN_LISTEN_PORT=5050
    ports:
      - "5050:5050"

volumes:
  db-postgres:
    driver: local