services:
  raw_data:
    build:
      context: .
      dockerfile: raw_data/Dockerfile
    hostname: raw_data
    container_name: raw_data
    depends_on:
      - db_postgres
    ports:
      - "8000:8000"
    volumes:
      - ./raw_data:/home/app/raw_data
      - ./common:/home/app/common

  risk:
    build:
      context: .
      dockerfile: risk/Dockerfile
    hostname: risk
    container_name: risk
    depends_on:
      - db_postgres
    ports:
      - "8100:8000"
    volumes:
      - ./risk:/home/app/risk
      - ./common:/home/app/common

  rules:
    build:
      context: .
      dockerfile: rules/Dockerfile
    hostname: rules
    container_name: rules
    depends_on:
      - db_postgres
    ports:
      - "8200:8000"
    volumes:
      - ./rules:/home/app/rules
      - ./common:/home/app/common

  positions:
    build:
      context: .
      dockerfile: positions/Dockerfile
    hostname: positions
    container_name: positions
    depends_on:
      - db_postgres
      - risk
    ports:
      - "8300:8000"
    volumes:
      - ./positions:/home/app/positions
      - ./common:/home/app/common

  forecast:
    build:
      context: .
      dockerfile: forecast/Dockerfile
    hostname: forecast
    container_name: forecast
    depends_on:
      - db_postgres
    ports:
      - "8400:8000"
    volumes:
      - ./forecast:/home/app/forecast
      - ./common:/home/app/common

  db_postgres:
    image: timescale/timescaledb:latest-pg16
    container_name: postgres
    hostname: ${DB_HOST}
    restart: on-failure
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - db-postgres:/var/lib/postgresql/data
      - ./database/data:/data:rw

  pg-admin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@email.com
      - PGADMIN_DEFAULT_PASSWORD=admin
      - PGADMIN_LISTEN_PORT=5050
    ports:
      - "5050:5050"

  redis:
    image: redis:latest
    container_name: "redis"
    hostname: "redis"
    restart: always
    ports:
      - 6380:6379

volumes:
  db-postgres:
    driver: local
  redis:
    driver: local
