[tool.pytest.ini_options]
minversion = "6.0"
addopts = "-ra --cov=src --cov-report=term-missing:skip-covered --import-mode=importlib"
testpaths = [
    "common/tests",
    "data_management/tests"
]
pythonpath = [
    ".",
    "data_management",
    "common"
]