"""Update models

Revision ID: 0f8d6ffeda2c
Revises: c2f6bf2a790d
Create Date: 2024-03-07 23:33:38.627637

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0f8d6ffeda2c'
down_revision: Union[str, None] = 'c2f6bf2a790d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tradable_instruments')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tradable_instruments',
    sa.Column('symbol', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('symbol', name='tradable_instruments_pkey')
    )
    # ### end Alembic commands ###
