"""Raw data indexes was added

Revision ID: 3ec6389ee11c
Revises: 5f9525f3a583
Create Date: 2024-04-01 21:57:15.267447

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes



# revision identifiers, used by Alembic.
revision: str = '3ec6389ee11c'
down_revision: Union[str, None] = '5f9525f3a583'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_adjusted_prices_date_time'), 'adjusted_prices', ['date_time'], unique=False)
    op.create_index(op.f('ix_adjusted_prices_symbol'), 'adjusted_prices', ['symbol'], unique=False)
    op.create_index(op.f('ix_fx_prices_date_time'), 'fx_prices', ['date_time'], unique=False)
    op.create_index(op.f('ix_fx_prices_symbol'), 'fx_prices', ['symbol'], unique=False)
    op.create_index(op.f('ix_multiple_prices_date_time'), 'multiple_prices', ['date_time'], unique=False)
    op.create_index(op.f('ix_multiple_prices_symbol'), 'multiple_prices', ['symbol'], unique=False)
    op.create_index(op.f('ix_roll_calendars_date_time'), 'roll_calendars', ['date_time'], unique=False)
    op.create_index(op.f('ix_roll_calendars_symbol'), 'roll_calendars', ['symbol'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_roll_calendars_symbol'), table_name='roll_calendars')
    op.drop_index(op.f('ix_roll_calendars_date_time'), table_name='roll_calendars')
    op.drop_index(op.f('ix_multiple_prices_symbol'), table_name='multiple_prices')
    op.drop_index(op.f('ix_multiple_prices_date_time'), table_name='multiple_prices')
    op.drop_index(op.f('ix_fx_prices_symbol'), table_name='fx_prices')
    op.drop_index(op.f('ix_fx_prices_date_time'), table_name='fx_prices')
    op.drop_index(op.f('ix_adjusted_prices_symbol'), table_name='adjusted_prices')
    op.drop_index(op.f('ix_adjusted_prices_date_time'), table_name='adjusted_prices')
    # ### end Alembic commands ###
