"""Update models

Revision ID: 4a1304d0adee
Revises: b2fcc1cb57e2
Create Date: 2024-03-10 12:20:19.016072

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes



# revision identifiers, used by Alembic.
revision: str = '4a1304d0adee'
down_revision: Union[str, None] = 'b2fcc1cb57e2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dailyvolnormalisedpriceforassetclass',
    sa.Column('date_time', sa.DateTime(), nullable=False),
    sa.Column('asset_clas', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('normalized_volatility', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('date_time')
    )
    op.create_table('dailyreturnsvolatility',
    sa.Column('date_time', sa.DateTime(), nullable=False),
    sa.Column('symbol', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('daily_returns_volatility', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['symbol'], ['instrumentconfig.symbol'], ),
    sa.PrimaryKeyConstraint('date_time', 'symbol')
    )
    op.create_table('dailyvolnormalizedreturns',
    sa.Column('date_time', sa.DateTime(), nullable=False),
    sa.Column('symbol', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('normalized_volatility', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['symbol'], ['instrumentconfig.symbol'], ),
    sa.PrimaryKeyConstraint('date_time', 'symbol')
    )
    op.create_table('instrumentvolatility',
    sa.Column('date_time', sa.DateTime(), nullable=False),
    sa.Column('symbol', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('instrument_volatility', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['symbol'], ['instrumentconfig.symbol'], ),
    sa.PrimaryKeyConstraint('date_time', 'symbol')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('instrumentvolatility')
    op.drop_table('dailyvolnormalizedreturns')
    op.drop_table('dailyreturnsvolatility')
    op.drop_table('dailyvolnormalisedpriceforassetclass')
    # ### end Alembic commands ###
