"""Update models

Revision ID: 535618e807b5
Revises: f05f293e7d12
Create Date: 2024-03-16 11:19:42.584574

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes

from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '535618e807b5'
down_revision: Union[str, None] = 'f05f293e7d12'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('fx_prices')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fx_prices',
    sa.Column('date_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('symbol', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('date_time', name='fx_prices_pkey')
    )
    # ### end Alembic commands ###
