"""Update models

Revision ID: 6faea8f224d6
Revises: 
Create Date: 2024-04-06 20:24:12.774454

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes



# revision identifiers, used by Alembic.
revision: str = '6faea8f224d6'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_vol_normalised_price_for_asset_class',
    sa.Column('date_time', sa.DateTime(), nullable=False),
    sa.Column('asset_class', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('vol_normalized_price_for_asset', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('date_time', 'asset_class')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('daily_vol_normalised_price_for_asset_class')
    # ### end Alembic commands ###
