"""Update models

Revision ID: 8c156973e278
Revises: 61f296c41abb
Create Date: 2024-03-16 11:18:25.542966

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes



# revision identifiers, used by Alembic.
revision: str = '8c156973e278'
down_revision: Union[str, None] = '61f296c41abb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('fx_prices', 'symbol')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fx_prices', sa.Column('symbol', sa.VARCHAR(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
