"""Update models

Revision ID: a35781fdd9e2
Revises: e1b1b2dbd440
Create Date: 2024-03-12 00:01:08.134662

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes

from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a35781fdd9e2'
down_revision: Union[str, None] = 'e1b1b2dbd440'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fxprices',
    sa.Column('date_time', sa.DateTime(), nullable=False),
    sa.Column('symbol', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['symbol'], ['instrumentconfig.symbol'], ),
    sa.PrimaryKeyConstraint('date_time', 'symbol')
    )
    op.create_table('multipleprices',
    sa.Column('date_time', sa.DateTime(), nullable=False),
    sa.Column('symbol', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('carry', sa.Float(), nullable=False),
    sa.Column('carry_contract', sa.Integer(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('price_contract', sa.Integer(), nullable=False),
    sa.Column('forward', sa.Float(), nullable=False),
    sa.Column('forward_contract', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['symbol'], ['instrumentconfig.symbol'], ),
    sa.PrimaryKeyConstraint('date_time', 'symbol')
    )
    op.drop_table('fxpricesmodel')
    op.drop_table('multiplepricesmodel')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('multiplepricesmodel',
    sa.Column('date_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('symbol', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('carry', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('carry_contract', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('price_contract', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('forward', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('forward_contract', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['symbol'], ['instrumentconfig.symbol'], name='multiplepricesmodel_symbol_fkey'),
    sa.PrimaryKeyConstraint('date_time', 'symbol', name='multiplepricesmodel_pkey')
    )
    op.create_table('fxpricesmodel',
    sa.Column('date_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('symbol', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['symbol'], ['instrumentconfig.symbol'], name='fxpricesmodel_symbol_fkey'),
    sa.PrimaryKeyConstraint('date_time', 'symbol', name='fxpricesmodel_pkey')
    )
    op.drop_table('multipleprices')
    op.drop_table('fxprices')
    # ### end Alembic commands ###
