"""Update models

Revision ID: a6562fa8ef90
Revises: 9e5d93a27ff3
Create Date: 2024-03-16 10:47:27.300083

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes



# revision identifiers, used by Alembic.
revision: str = 'a6562fa8ef90'
down_revision: Union[str, None] = '9e5d93a27ff3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('multiple_prices', sa.Column('carry_contract', sa.Integer(), nullable=False))
    op.add_column('multiple_prices', sa.Column('price', sa.Float(), nullable=False))
    op.add_column('multiple_prices', sa.Column('price_contract', sa.Integer(), nullable=False))
    op.add_column('multiple_prices', sa.Column('forward', sa.Float(), nullable=False))
    op.add_column('multiple_prices', sa.Column('forward_contract', sa.Integer(), nullable=False))
    op.add_column('roll_calendars', sa.Column('next_contract', sa.Integer(), nullable=False))
    op.add_column('roll_calendars', sa.Column('carry_contract', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('roll_calendars', 'carry_contract')
    op.drop_column('roll_calendars', 'next_contract')
    op.drop_column('multiple_prices', 'forward_contract')
    op.drop_column('multiple_prices', 'forward')
    op.drop_column('multiple_prices', 'price_contract')
    op.drop_column('multiple_prices', 'price')
    op.drop_column('multiple_prices', 'carry_contract')
    # ### end Alembic commands ###
