"""Update models

Revision ID: a85f45bf41da
Revises: 4a1304d0adee
Create Date: 2024-03-11 18:47:29.383899

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes



# revision identifiers, used by Alembic.
revision: str = 'a85f45bf41da'
down_revision: Union[str, None] = '4a1304d0adee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('instrumentmetadata', 'duration')
    op.drop_column('instrumentmetadata', 'country')
    op.drop_column('instrumentmetadata', 'sub_sub_class')
    op.drop_column('instrumentmetadata', 'style')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('instrumentmetadata', sa.Column('style', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('instrumentmetadata', sa.Column('sub_sub_class', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('instrumentmetadata', sa.Column('country', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('instrumentmetadata', sa.Column('duration', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
