"""Update models

Revision ID: bcde74c4f65d
Revises: 669cca0550c0
Create Date: 2024-04-26 14:57:10.115532

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes

from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'bcde74c4f65d'
down_revision: Union[str, None] = '669cca0550c0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('instrument_currency_volatility',
    sa.Column('date_time', sa.DateTime(), nullable=False),
    sa.Column('symbol', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('instrument_volatility', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['symbol'], ['instrument_config.symbol'], ),
    sa.PrimaryKeyConstraint('date_time', 'symbol')
    )
    op.drop_table('instrument_volatility')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('instrument_volatility',
    sa.Column('date_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('symbol', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('instrument_volatility', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['symbol'], ['instrument_config.symbol'], name='instrument_volatility_symbol_fkey'),
    sa.PrimaryKeyConstraint('date_time', 'symbol', name='instrument_volatility_pkey')
    )
    op.drop_table('instrument_currency_volatility')
    # ### end Alembic commands ###
