"""Update models

Revision ID: dd32d513232c
Revises: 1851fc2040e2
Create Date: 2024-02-18 16:32:06.875969

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dd32d513232c'
down_revision: Union[str, None] = '1851fc2040e2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('spread_costs',
    sa.Column('symbol', sa.String(length=50), nullable=False),
    sa.Column('spread_costs', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['symbol'], ['instrument_config.symbol'], ),
    sa.PrimaryKeyConstraint('symbol')
    )
    op.drop_table('spread_cost')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('spread_cost',
    sa.Column('symbol', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('spread_cost', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['symbol'], ['instrument_config.symbol'], name='spread_cost_symbol_fkey'),
    sa.PrimaryKeyConstraint('symbol', name='spread_cost_pkey')
    )
    op.drop_table('spread_costs')
    # ### end Alembic commands ###
