"""Update models

Revision ID: e1b1b2dbd440
Revises: a85f45bf41da
Create Date: 2024-03-11 19:23:32.616762

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes



# revision identifiers, used by Alembic.
revision: str = 'e1b1b2dbd440'
down_revision: Union[str, None] = 'a85f45bf41da'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('spreadcosts', sa.Column('spread_costs', sa.Float(), nullable=False))
    op.drop_column('spreadcosts', 'percentage')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('spreadcosts', sa.Column('percentage', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.drop_column('spreadcosts', 'spread_costs')
    # ### end Alembic commands ###
