"""Update models

Revision ID: f05f293e7d12
Revises: 8c156973e278
Create Date: 2024-03-16 11:18:51.608289

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes



# revision identifiers, used by Alembic.
revision: str = 'f05f293e7d12'
down_revision: Union[str, None] = '8c156973e278'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fx_prices', sa.Column('symbol', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('fx_prices', 'symbol')
    # ### end Alembic commands ###
