"""Update models

Revision ID: f5f3304428e9
Revises: 2e5c87d61ddd
Create Date: 2024-03-12 20:34:44.811669

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes



# revision identifiers, used by Alembic.
revision: str = 'f5f3304428e9'
down_revision: Union[str, None] = '2e5c87d61ddd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rollcalendars',
    sa.Column('date_time', sa.DateTime(), nullable=False),
    sa.Column('symbol', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('current_contract', sa.Integer(), nullable=False),
    sa.Column('next_contract', sa.Integer(), nullable=False),
    sa.Column('carry_contract', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['symbol'], ['instrumentconfig.symbol'], ),
    sa.PrimaryKeyConstraint('date_time', 'symbol')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rollcalendars')
    # ### end Alembic commands ###
