# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import absolute_skew_deviation_pb2 as absolute__skew__deviation__pb2

GRPC_GENERATED_VERSION = '1.68.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in absolute_skew_deviation_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class AbsoluteSkewDeviationStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.get_absolute_skew_deviation = channel.unary_unary(
                '/absolute_skew_deviation.AbsoluteSkewDeviation/get_absolute_skew_deviation',
                request_serializer=absolute__skew__deviation__pb2.AbsoluteSkewDeviationRequest.SerializeToString,
                response_deserializer=absolute__skew__deviation__pb2.AbsoluteSkewDeviationResponse.FromString,
                _registered_method=True)


class AbsoluteSkewDeviationServicer(object):
    """Missing associated documentation comment in .proto file."""

    def get_absolute_skew_deviation(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AbsoluteSkewDeviationServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'get_absolute_skew_deviation': grpc.unary_unary_rpc_method_handler(
                    servicer.get_absolute_skew_deviation,
                    request_deserializer=absolute__skew__deviation__pb2.AbsoluteSkewDeviationRequest.FromString,
                    response_serializer=absolute__skew__deviation__pb2.AbsoluteSkewDeviationResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'absolute_skew_deviation.AbsoluteSkewDeviation', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('absolute_skew_deviation.AbsoluteSkewDeviation', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AbsoluteSkewDeviation(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def get_absolute_skew_deviation(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/absolute_skew_deviation.AbsoluteSkewDeviation/get_absolute_skew_deviation',
            absolute__skew__deviation__pb2.AbsoluteSkewDeviationRequest.SerializeToString,
            absolute__skew__deviation__pb2.AbsoluteSkewDeviationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
