# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: cumulative_daily_vol_norm_returns.proto
# Protobuf Python Version: 5.28.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    1,
    '',
    'cumulative_daily_vol_norm_returns.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\'cumulative_daily_vol_norm_returns.proto\x12\x08raw_data\"6\n$CumulativeDailyVolNormReturnsRequest\x12\x0e\n\x06symbol\x18\x01 \x01(\t\"7\n%CumulativeDailyVolNormReturnsResponse\x12\x0e\n\x06series\x18\x01 \x01(\x0c\x32\xaa\x01\n\x1d\x43umulativeDailyVolNormReturns\x12\x88\x01\n%get_cumulative_daily_vol_norm_returns\x12..raw_data.CumulativeDailyVolNormReturnsRequest\x1a/.raw_data.CumulativeDailyVolNormReturnsResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'cumulative_daily_vol_norm_returns_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CUMULATIVEDAILYVOLNORMRETURNSREQUEST']._serialized_start=53
  _globals['_CUMULATIVEDAILYVOLNORMRETURNSREQUEST']._serialized_end=107
  _globals['_CUMULATIVEDAILYVOLNORMRETURNSRESPONSE']._serialized_start=109
  _globals['_CUMULATIVEDAILYVOLNORMRETURNSRESPONSE']._serialized_end=164
  _globals['_CUMULATIVEDAILYVOLNORMRETURNS']._serialized_start=167
  _globals['_CUMULATIVEDAILYVOLNORMRETURNS']._serialized_end=337
# @@protoc_insertion_point(module_scope)
