# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: daily_returns_vol.proto
# Protobuf Python Version: 5.28.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    1,
    '',
    'daily_returns_vol.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17\x64\x61ily_returns_vol.proto\x12\x08raw_data\"(\n\x16\x44\x61ilyReturnsVolRequest\x12\x0e\n\x06symbol\x18\x01 \x01(\t\")\n\x17\x44\x61ilyReturnsVolResponse\x12\x0e\n\x06series\x18\x01 \x01(\x0c\x32o\n\x0f\x44\x61ilyReturnsVol\x12\\\n\x15get_daily_returns_vol\x12 .raw_data.DailyReturnsVolRequest\x1a!.raw_data.DailyReturnsVolResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'daily_returns_vol_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_DAILYRETURNSVOLREQUEST']._serialized_start=37
  _globals['_DAILYRETURNSVOLREQUEST']._serialized_end=77
  _globals['_DAILYRETURNSVOLRESPONSE']._serialized_start=79
  _globals['_DAILYRETURNSVOLRESPONSE']._serialized_end=120
  _globals['_DAILYRETURNSVOL']._serialized_start=122
  _globals['_DAILYRETURNSVOL']._serialized_end=233
# @@protoc_insertion_point(module_scope)
