# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: instrument_currency_vol.proto
# Protobuf Python Version: 5.28.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    1,
    '',
    'instrument_currency_vol.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1dinstrument_currency_vol.proto\x12\x08raw_data\".\n\x1cInstrumentCurrencyVolRequest\x12\x0e\n\x06symbol\x18\x01 \x01(\t\"/\n\x1dInstrumentCurrencyVolResponse\x12\x0e\n\x06series\x18\x01 \x01(\x0c\x32\x8e\x01\n\x1cInstrumentCurrencyVolHandler\x12n\n\x1bget_instrument_currency_vol\x12&.raw_data.InstrumentCurrencyVolRequest\x1a\'.raw_data.InstrumentCurrencyVolResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'instrument_currency_vol_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_INSTRUMENTCURRENCYVOLREQUEST']._serialized_start=43
  _globals['_INSTRUMENTCURRENCYVOLREQUEST']._serialized_end=89
  _globals['_INSTRUMENTCURRENCYVOLRESPONSE']._serialized_start=91
  _globals['_INSTRUMENTCURRENCYVOLRESPONSE']._serialized_end=138
  _globals['_INSTRUMENTCURRENCYVOLHANDLER']._serialized_start=141
  _globals['_INSTRUMENTCURRENCYVOLHANDLER']._serialized_end=283
# @@protoc_insertion_point(module_scope)
