# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: normalized_prices.proto
# Protobuf Python Version: 5.28.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    1,
    '',
    'normalized_prices.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17normalized_prices.proto\x12\x08raw_data\")\n\x17NormalizedPricesRequest\x12\x0e\n\x06symbol\x18\x01 \x01(\t\"*\n\x18NormalizedPricesResponse\x12\x0e\n\x06series\x18\x01 \x01(\x0c\x32r\n\x10NormalizedPrices\x12^\n\x15get_normalized_prices\x12!.raw_data.NormalizedPricesRequest\x1a\".raw_data.NormalizedPricesResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'normalized_prices_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_NORMALIZEDPRICESREQUEST']._serialized_start=37
  _globals['_NORMALIZEDPRICESREQUEST']._serialized_end=78
  _globals['_NORMALIZEDPRICESRESPONSE']._serialized_start=80
  _globals['_NORMALIZEDPRICESRESPONSE']._serialized_end=122
  _globals['_NORMALIZEDPRICES']._serialized_start=124
  _globals['_NORMALIZEDPRICES']._serialized_end=238
# @@protoc_insertion_point(module_scope)
