"""Update models

Revision ID: 034c4c601cd4
Revises: e6c2ad3b2bbb
Create Date: 2023-11-20 11:08:33.615502

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '034c4c601cd4'
down_revision: Union[str, None] = 'e6c2ad3b2bbb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
