"""Update models

Revision ID: 251764be9243
Revises: 27674bf249b3
Create Date: 2023-11-30 16:54:14.588788

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "251764be9243"
down_revision: Union[str, None] = "27674bf249b3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "instrument_metadata", sa.Column("style", sa.String(length=50), nullable=True)
    )
    op.add_column(
        "instrument_metadata", sa.Column("country", sa.String(length=50), nullable=True)
    )
    op.add_column(
        "instrument_metadata",
        sa.Column("duration", sa.String(length=50), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("instrument_metadata", "duration")
    op.drop_column("instrument_metadata", "country")
    op.drop_column("instrument_metadata", "style")
    # ### end Alembic commands ###
