"""Update db

Revision ID: 27674bf249b3
Revises: 18869f56513c
Create Date: 2023-11-27 17:49:35.034902

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '27674bf249b3'
down_revision: Union[str, None] = '18869f56513c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cumulative_daily_vol_normalized_returns',
    sa.Column('unix_date_time', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=50), nullable=False),
    sa.Column('normalized_volatility', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['symbol'], ['instrument_config.symbol'], ),
    sa.PrimaryKeyConstraint('unix_date_time', 'symbol')
    )
    op.create_table('daily_returns_volatility',
    sa.Column('unix_date_time', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=50), nullable=False),
    sa.Column('daily_returns_volatility', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['symbol'], ['instrument_config.symbol'], ),
    sa.PrimaryKeyConstraint('unix_date_time', 'symbol')
    )
    op.drop_table('robust_volatility')
    op.add_column('instrument_volatility', sa.Column('instrument_volatility', sa.Float(), nullable=True))
    op.drop_column('instrument_volatility', 'volatility')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('instrument_volatility', sa.Column('volatility', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_column('instrument_volatility', 'instrument_volatility')
    op.create_table('robust_volatility',
    sa.Column('unix_date_time', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('symbol', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('volatility', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['symbol'], ['instrument_config.symbol'], name='robust_volatility_symbol_fkey'),
    sa.PrimaryKeyConstraint('unix_date_time', 'symbol', name='robust_volatility_pkey')
    )
    op.drop_table('daily_returns_volatility')
    op.drop_table('cumulative_daily_vol_normalized_returns')
    # ### end Alembic commands ###
