"""Update models

Revision ID: 86786f220598
Revises: 251764be9243
Create Date: 2023-12-04 18:05:18.472496

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '86786f220598'
down_revision: Union[str, None] = '251764be9243'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_vol_normalised_price_for_asset_class',
    sa.Column('unix_date_time', sa.Integer(), nullable=False),
    sa.Column('asset_class', sa.String(length=50), nullable=False),
    sa.Column('normalized_volatility', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('unix_date_time', 'asset_class')
    )
    op.create_table('daily_vol_normalized_returns',
    sa.Column('unix_date_time', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=50), nullable=False),
    sa.Column('normalized_volatility', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['symbol'], ['instrument_config.symbol'], ),
    sa.PrimaryKeyConstraint('unix_date_time', 'symbol')
    )
    op.create_table('normalised_price_for_asset_class',
    sa.Column('unix_date_time', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=50), nullable=False),
    sa.Column('normalized_price', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['symbol'], ['instrument_config.symbol'], ),
    sa.PrimaryKeyConstraint('unix_date_time', 'symbol')
    )
    op.drop_table('cumulative_daily_vol_normalized_returns')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cumulative_daily_vol_normalized_returns',
    sa.Column('unix_date_time', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('symbol', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('normalized_volatility', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['symbol'], ['instrument_config.symbol'], name='cumulative_daily_vol_normalized_returns_symbol_fkey'),
    sa.PrimaryKeyConstraint('unix_date_time', 'symbol', name='cumulative_daily_vol_normalized_returns_pkey')
    )
    op.drop_table('normalised_price_for_asset_class')
    op.drop_table('daily_vol_normalized_returns')
    op.drop_table('daily_vol_normalised_price_for_asset_class')
    # ### end Alembic commands ###
