"""Update models

Revision ID: a18d20193348
Revises: 86786f220598
Create Date: 2023-12-16 17:12:22.173699

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a18d20193348'
down_revision: Union[str, None] = '86786f220598'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tradable_instruments',
    sa.Column('symbol', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('symbol')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tradable_instruments')
    # ### end Alembic commands ###
