"""Update models

Revision ID: e6c2ad3b2bbb
Revises: 4bf57d5ce382
Create Date: 2023-11-19 23:38:04.402633

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e6c2ad3b2bbb'
down_revision: Union[str, None] = '4bf57d5ce382'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'adjusted_prices', 'instrument_config', ['symbol'], ['symbol'])
    op.create_foreign_key(None, 'fx_prices', 'instrument_config', ['symbol'], ['symbol'])
    op.create_foreign_key(None, 'instrument_metadata', 'instrument_config', ['symbol'], ['symbol'])
    op.create_foreign_key(None, 'instrument_volatility', 'instrument_config', ['symbol'], ['symbol'])
    op.create_foreign_key(None, 'multiple_prices', 'instrument_config', ['symbol'], ['symbol'])
    op.create_foreign_key(None, 'robust_volatility', 'instrument_config', ['symbol'], ['symbol'])
    op.create_foreign_key(None, 'roll_calendars', 'instrument_config', ['symbol'], ['symbol'])
    op.create_foreign_key(None, 'roll_config', 'instrument_config', ['symbol'], ['symbol'])
    op.create_foreign_key(None, 'spread_cost', 'instrument_config', ['symbol'], ['symbol'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'spread_cost', type_='foreignkey')
    op.drop_constraint(None, 'roll_config', type_='foreignkey')
    op.drop_constraint(None, 'roll_calendars', type_='foreignkey')
    op.drop_constraint(None, 'robust_volatility', type_='foreignkey')
    op.drop_constraint(None, 'multiple_prices', type_='foreignkey')
    op.drop_constraint(None, 'instrument_volatility', type_='foreignkey')
    op.drop_constraint(None, 'instrument_metadata', type_='foreignkey')
    op.drop_constraint(None, 'fx_prices', type_='foreignkey')
    op.drop_constraint(None, 'adjusted_prices', type_='foreignkey')
    # ### end Alembic commands ###
