"""Update models

Revision ID: f48d93b34044
Revises: 
Create Date: 2023-11-14 15:09:40.197638

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f48d93b34044'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('adjusted_prices',
    sa.Column('unix_date_time', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=50), nullable=False),
    sa.Column('price', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('unix_date_time', 'symbol')
    )
    op.create_table('fx_prices',
    sa.Column('unix_date_time', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=50), nullable=False),
    sa.Column('price', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('unix_date_time', 'symbol')
    )
    op.create_table('instrument_config',
    sa.Column('symbol', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('pointsize', sa.Float(), nullable=True),
    sa.Column('currency', sa.String(length=10), nullable=True),
    sa.Column('asset_class', sa.String(length=50), nullable=True),
    sa.Column('per_block', sa.Float(), nullable=True),
    sa.Column('percentage', sa.Float(), nullable=True),
    sa.Column('per_trade', sa.Integer(), nullable=True),
    sa.Column('region', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('symbol')
    )
    op.create_table('instrument_metadata',
    sa.Column('symbol', sa.String(length=50), nullable=False),
    sa.Column('asset_class', sa.String(length=50), nullable=True),
    sa.Column('sub_class', sa.String(length=50), nullable=True),
    sa.Column('sub_sub_class', sa.String(length=50), nullable=True),
    sa.Column('description', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('symbol')
    )
    op.create_table('instrument_volatility',
    sa.Column('unix_date_time', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=50), nullable=False),
    sa.Column('volatility', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('unix_date_time', 'symbol')
    )
    op.create_table('multiple_prices',
    sa.Column('unix_date_time', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=50), nullable=False),
    sa.Column('carry', sa.Float(), nullable=True),
    sa.Column('carry_contract', sa.Integer(), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('price_contract', sa.Integer(), nullable=True),
    sa.Column('forward', sa.Float(), nullable=True),
    sa.Column('forward_contract', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('unix_date_time', 'symbol')
    )
    op.create_table('robust_volatility',
    sa.Column('unix_date_time', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=50), nullable=False),
    sa.Column('volatility', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('unix_date_time', 'symbol')
    )
    op.create_table('roll_calendars',
    sa.Column('unix_date_time', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=50), nullable=False),
    sa.Column('current_contract', sa.Integer(), nullable=True),
    sa.Column('next_contract', sa.Integer(), nullable=True),
    sa.Column('carry_contract', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('unix_date_time', 'symbol')
    )
    op.create_table('roll_config',
    sa.Column('symbol', sa.String(length=50), nullable=False),
    sa.Column('hold_roll_cycle', sa.String(length=50), nullable=True),
    sa.Column('roll_offset_days', sa.Integer(), nullable=True),
    sa.Column('carry_offset', sa.Integer(), nullable=True),
    sa.Column('priced_roll_cycle', sa.String(length=50), nullable=True),
    sa.Column('expiry_offset', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('symbol')
    )
    op.create_table('spread_cost',
    sa.Column('symbol', sa.String(length=50), nullable=False),
    sa.Column('spread_cost', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('symbol')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('spread_cost')
    op.drop_table('roll_config')
    op.drop_table('roll_calendars')
    op.drop_table('robust_volatility')
    op.drop_table('multiple_prices')
    op.drop_table('instrument_volatility')
    op.drop_table('instrument_metadata')
    op.drop_table('instrument_config')
    op.drop_table('fx_prices')
    op.drop_table('adjusted_prices')
    # ### end Alembic commands ###
