# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import accel_pb2 as accel__pb2

GRPC_GENERATED_VERSION = '1.68.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in accel_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class AccelStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.get_accel = channel.unary_unary(
                '/rules.Accel/get_accel',
                request_serializer=accel__pb2.AccelRequest.SerializeToString,
                response_deserializer=accel__pb2.AccelResponse.FromString,
                _registered_method=True)


class AccelServicer(object):
    """Missing associated documentation comment in .proto file."""

    def get_accel(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AccelServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'get_accel': grpc.unary_unary_rpc_method_handler(
                    servicer.get_accel,
                    request_deserializer=accel__pb2.AccelRequest.FromString,
                    response_serializer=accel__pb2.AccelResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'rules.Accel', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('rules.Accel', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Accel(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def get_accel(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rules.Accel/get_accel',
            accel__pb2.AccelRequest.SerializeToString,
            accel__pb2.AccelResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
