# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: asserttrend.proto
# Protobuf Python Version: 5.28.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    1,
    '',
    'asserttrend.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11\x61sserttrend.proto\x12\x05rules\"\x89\x01\n\x12\x41ssertTrendRequest\x12\x0e\n\x06symbol\x18\x01 \x01(\t\x12\r\n\x05lfast\x18\x02 \x01(\x05\x12\r\n\x05lslow\x18\x03 \x01(\x05\x12\x17\n\x0fuse_attenuation\x18\x04 \x01(\x08\x12\x16\n\x0escaling_factor\x18\x05 \x01(\x02\x12\x14\n\x0cscaling_type\x18\x06 \x01(\t\"%\n\x13\x41ssertTrendResponse\x12\x0e\n\x06series\x18\x01 \x01(\x0c\x32W\n\x0b\x41ssertTrend\x12H\n\x0fget_asserttrend\x12\x19.rules.AssertTrendRequest\x1a\x1a.rules.AssertTrendResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'asserttrend_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ASSERTTRENDREQUEST']._serialized_start=29
  _globals['_ASSERTTRENDREQUEST']._serialized_end=166
  _globals['_ASSERTTRENDRESPONSE']._serialized_start=168
  _globals['_ASSERTTRENDRESPONSE']._serialized_end=205
  _globals['_ASSERTTREND']._serialized_start=207
  _globals['_ASSERTTREND']._serialized_end=294
# @@protoc_insertion_point(module_scope)
