"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins
import google.protobuf.descriptor
import google.protobuf.message
import typing

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class BreakoutRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    SYMBOL_FIELD_NUMBER: builtins.int
    LOOKBACK_FIELD_NUMBER: builtins.int
    USE_ATTENUATION_FIELD_NUMBER: builtins.int
    SCALING_FACTOR_FIELD_NUMBER: builtins.int
    SCALING_TYPE_FIELD_NUMBER: builtins.int
    symbol: builtins.str
    lookback: builtins.int
    use_attenuation: builtins.bool
    scaling_factor: builtins.float
    scaling_type: builtins.str
    def __init__(
        self,
        *,
        symbol: builtins.str = ...,
        lookback: builtins.int = ...,
        use_attenuation: builtins.bool = ...,
        scaling_factor: builtins.float = ...,
        scaling_type: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["lookback", b"lookback", "scaling_factor", b"scaling_factor", "scaling_type", b"scaling_type", "symbol", b"symbol", "use_attenuation", b"use_attenuation"]) -> None: ...

global___BreakoutRequest = BreakoutRequest

@typing.final
class BreakoutResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    SERIES_FIELD_NUMBER: builtins.int
    series: builtins.bytes
    def __init__(
        self,
        *,
        series: builtins.bytes = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["series", b"series"]) -> None: ...

global___BreakoutResponse = BreakoutResponse
