# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: breakout.proto
# Protobuf Python Version: 5.28.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    1,
    '',
    'breakout.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0e\x62reakout.proto\x12\x05rules\"z\n\x0f\x42reakoutRequest\x12\x0e\n\x06symbol\x18\x01 \x01(\t\x12\x10\n\x08lookback\x18\x02 \x01(\x05\x12\x17\n\x0fuse_attenuation\x18\x03 \x01(\x08\x12\x16\n\x0escaling_factor\x18\x04 \x01(\x02\x12\x14\n\x0cscaling_type\x18\x05 \x01(\t\"\"\n\x10\x42reakoutResponse\x12\x0e\n\x06series\x18\x01 \x01(\x0c\x32K\n\x08\x42reakout\x12?\n\x0cget_breakout\x12\x16.rules.BreakoutRequest\x1a\x17.rules.BreakoutResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'breakout_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_BREAKOUTREQUEST']._serialized_start=25
  _globals['_BREAKOUTREQUEST']._serialized_end=147
  _globals['_BREAKOUTRESPONSE']._serialized_start=149
  _globals['_BREAKOUTRESPONSE']._serialized_end=183
  _globals['_BREAKOUT']._serialized_start=185
  _globals['_BREAKOUT']._serialized_end=260
# @@protoc_insertion_point(module_scope)
