# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: carry.proto
# Protobuf Python Version: 5.28.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    1,
    '',
    'carry.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0b\x63\x61rry.proto\x12\x05rules\"z\n\x0c\x43\x61rryRequest\x12\x0e\n\x06symbol\x18\x01 \x01(\t\x12\x13\n\x0bsmooth_days\x18\x02 \x01(\x05\x12\x17\n\x0fuse_attenuation\x18\x03 \x01(\x08\x12\x16\n\x0escaling_factor\x18\x04 \x01(\x02\x12\x14\n\x0cscaling_type\x18\x05 \x01(\t\"\x1f\n\rCarryResponse\x12\x0e\n\x06series\x18\x01 \x01(\x0c\x32?\n\x05\x43\x61rry\x12\x36\n\tget_carry\x12\x13.rules.CarryRequest\x1a\x14.rules.CarryResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'carry_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CARRYREQUEST']._serialized_start=22
  _globals['_CARRYREQUEST']._serialized_end=144
  _globals['_CARRYRESPONSE']._serialized_start=146
  _globals['_CARRYRESPONSE']._serialized_end=177
  _globals['_CARRY']._serialized_start=179
  _globals['_CARRY']._serialized_end=242
# @@protoc_insertion_point(module_scope)
