# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: cs_mean_reversion.proto
# Protobuf Python Version: 5.28.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    1,
    '',
    'cs_mean_reversion.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17\x63s_mean_reversion.proto\x12\x05rules\"\x80\x01\n\x16\x43SMeanReversionRequest\x12\x0e\n\x06symbol\x18\x01 \x01(\t\x12\x0f\n\x07horizon\x18\x02 \x01(\x05\x12\x17\n\x0fuse_attenuation\x18\x03 \x01(\x08\x12\x16\n\x0escaling_factor\x18\x04 \x01(\x02\x12\x14\n\x0cscaling_type\x18\x05 \x01(\t\")\n\x17\x43SMeanReversionResponse\x12\x0e\n\x06series\x18\x01 \x01(\x0c\x32i\n\x0f\x43SMeanReversion\x12V\n\x15get_cs_mean_reversion\x12\x1d.rules.CSMeanReversionRequest\x1a\x1e.rules.CSMeanReversionResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'cs_mean_reversion_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CSMEANREVERSIONREQUEST']._serialized_start=35
  _globals['_CSMEANREVERSIONREQUEST']._serialized_end=163
  _globals['_CSMEANREVERSIONRESPONSE']._serialized_start=165
  _globals['_CSMEANREVERSIONRESPONSE']._serialized_end=206
  _globals['_CSMEANREVERSION']._serialized_start=208
  _globals['_CSMEANREVERSION']._serialized_end=313
# @@protoc_insertion_point(module_scope)
