# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import fx_prices_pb2 as fx__prices__pb2

GRPC_GENERATED_VERSION = '1.68.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in fx_prices_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class FxPricesStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.get_fx_prices = channel.unary_unary(
                '/absolute_skew_deviation.FxPrices/get_fx_prices',
                request_serializer=fx__prices__pb2.FxPricesRequest.SerializeToString,
                response_deserializer=fx__prices__pb2.FxPricesResponse.FromString,
                _registered_method=True)


class FxPricesServicer(object):
    """Missing associated documentation comment in .proto file."""

    def get_fx_prices(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_FxPricesServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'get_fx_prices': grpc.unary_unary_rpc_method_handler(
                    servicer.get_fx_prices,
                    request_deserializer=fx__prices__pb2.FxPricesRequest.FromString,
                    response_serializer=fx__prices__pb2.FxPricesResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'absolute_skew_deviation.FxPrices', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('absolute_skew_deviation.FxPrices', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class FxPrices(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def get_fx_prices(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/absolute_skew_deviation.FxPrices/get_fx_prices',
            fx__prices__pb2.FxPricesRequest.SerializeToString,
            fx__prices__pb2.FxPricesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
