# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: median_carry_for_asset_class.proto
# Protobuf Python Version: 5.28.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    1,
    '',
    'median_carry_for_asset_class.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\"median_carry_for_asset_class.proto\x12\x08raw_data\"$\n\x12MedianCarryRequest\x12\x0e\n\x06symbol\x18\x01 \x01(\t\"%\n\x13MedianCarryResponse\x12\x0e\n\x06series\x18\x01 \x01(\x0c\x32^\n\x0bMedianCarry\x12O\n\x10get_median_carry\x12\x1c.raw_data.MedianCarryRequest\x1a\x1d.raw_data.MedianCarryResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'median_carry_for_asset_class_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_MEDIANCARRYREQUEST']._serialized_start=48
  _globals['_MEDIANCARRYREQUEST']._serialized_end=84
  _globals['_MEDIANCARRYRESPONSE']._serialized_start=86
  _globals['_MEDIANCARRYRESPONSE']._serialized_end=123
  _globals['_MEDIANCARRY']._serialized_start=125
  _globals['_MEDIANCARRY']._serialized_end=219
# @@protoc_insertion_point(module_scope)
