# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: momentum.proto
# Protobuf Python Version: 5.28.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    1,
    '',
    'momentum.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0emomentum.proto\x12\x05rules\"\x86\x01\n\x0fMomentumRequest\x12\x0e\n\x06symbol\x18\x01 \x01(\t\x12\r\n\x05lfast\x18\x02 \x01(\x05\x12\r\n\x05lslow\x18\x03 \x01(\x05\x12\x17\n\x0fuse_attenuation\x18\x04 \x01(\x08\x12\x16\n\x0escaling_factor\x18\x05 \x01(\x02\x12\x14\n\x0cscaling_type\x18\x06 \x01(\t\"\"\n\x10MomentumResponse\x12\x0e\n\x06series\x18\x01 \x01(\x0c\x32K\n\x08Momentum\x12?\n\x0cget_momentum\x12\x16.rules.MomentumRequest\x1a\x17.rules.MomentumResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'momentum_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_MOMENTUMREQUEST']._serialized_start=26
  _globals['_MOMENTUMREQUEST']._serialized_end=160
  _globals['_MOMENTUMRESPONSE']._serialized_start=162
  _globals['_MOMENTUMRESPONSE']._serialized_end=196
  _globals['_MOMENTUM']._serialized_start=198
  _globals['_MOMENTUM']._serialized_end=273
# @@protoc_insertion_point(module_scope)
