"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins
import google.protobuf.descriptor
import google.protobuf.message
import typing

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class SmoothCarryRequest(google.protobuf.message.Message):
    """--------------------
    Messages
    --------------------

    SmoothCarry service
    """

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    SYMBOL_FIELD_NUMBER: builtins.int
    symbol: builtins.str
    def __init__(
        self,
        *,
        symbol: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["symbol", b"symbol"]) -> None: ...

global___SmoothCarryRequest = SmoothCarryRequest

@typing.final
class SmoothCarryResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    SERIES_FIELD_NUMBER: builtins.int
    series: builtins.bytes
    def __init__(
        self,
        *,
        series: builtins.bytes = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["series", b"series"]) -> None: ...

global___SmoothCarryResponse = SmoothCarryResponse

@typing.final
class VolAttenuationRequest(google.protobuf.message.Message):
    """VolAttenuation service"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    SYMBOL_FIELD_NUMBER: builtins.int
    symbol: builtins.str
    def __init__(
        self,
        *,
        symbol: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["symbol", b"symbol"]) -> None: ...

global___VolAttenuationRequest = VolAttenuationRequest

@typing.final
class VolAttenuationResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    SERIES_FIELD_NUMBER: builtins.int
    series: builtins.bytes
    def __init__(
        self,
        *,
        series: builtins.bytes = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["series", b"series"]) -> None: ...

global___VolAttenuationResponse = VolAttenuationResponse

@typing.final
class FxPricesRequest(google.protobuf.message.Message):
    """FxPrices service"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    SYMBOL_FIELD_NUMBER: builtins.int
    BASE_CURRENCY_FIELD_NUMBER: builtins.int
    symbol: builtins.str
    base_currency: builtins.str
    def __init__(
        self,
        *,
        symbol: builtins.str = ...,
        base_currency: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["base_currency", b"base_currency", "symbol", b"symbol"]) -> None: ...

global___FxPricesRequest = FxPricesRequest

@typing.final
class FxPricesResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    SERIES_FIELD_NUMBER: builtins.int
    series: builtins.bytes
    def __init__(
        self,
        *,
        series: builtins.bytes = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["series", b"series"]) -> None: ...

global___FxPricesResponse = FxPricesResponse

@typing.final
class InstrumentCurrencyVolRequest(google.protobuf.message.Message):
    """InstrumentCurrencyVol service"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    SYMBOL_FIELD_NUMBER: builtins.int
    symbol: builtins.str
    def __init__(
        self,
        *,
        symbol: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["symbol", b"symbol"]) -> None: ...

global___InstrumentCurrencyVolRequest = InstrumentCurrencyVolRequest

@typing.final
class InstrumentCurrencyVolResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    SERIES_FIELD_NUMBER: builtins.int
    series: builtins.bytes
    def __init__(
        self,
        *,
        series: builtins.bytes = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["series", b"series"]) -> None: ...

global___InstrumentCurrencyVolResponse = InstrumentCurrencyVolResponse

@typing.final
class MedianCarryRequest(google.protobuf.message.Message):
    """MedianCarry service"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    SYMBOL_FIELD_NUMBER: builtins.int
    symbol: builtins.str
    def __init__(
        self,
        *,
        symbol: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["symbol", b"symbol"]) -> None: ...

global___MedianCarryRequest = MedianCarryRequest

@typing.final
class MedianCarryResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    SERIES_FIELD_NUMBER: builtins.int
    series: builtins.bytes
    def __init__(
        self,
        *,
        series: builtins.bytes = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["series", b"series"]) -> None: ...

global___MedianCarryResponse = MedianCarryResponse

@typing.final
class NormalizedPricesRequest(google.protobuf.message.Message):
    """NormalizedPrices service"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    SYMBOL_FIELD_NUMBER: builtins.int
    symbol: builtins.str
    def __init__(
        self,
        *,
        symbol: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["symbol", b"symbol"]) -> None: ...

global___NormalizedPricesRequest = NormalizedPricesRequest

@typing.final
class NormalizedPricesResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    SERIES_FIELD_NUMBER: builtins.int
    series: builtins.bytes
    def __init__(
        self,
        *,
        series: builtins.bytes = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["series", b"series"]) -> None: ...

global___NormalizedPricesResponse = NormalizedPricesResponse

@typing.final
class RawCarryRequest(google.protobuf.message.Message):
    """RawCarry service"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    SYMBOL_FIELD_NUMBER: builtins.int
    symbol: builtins.str
    def __init__(
        self,
        *,
        symbol: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["symbol", b"symbol"]) -> None: ...

global___RawCarryRequest = RawCarryRequest

@typing.final
class RawCarryResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    SERIES_FIELD_NUMBER: builtins.int
    series: builtins.bytes
    def __init__(
        self,
        *,
        series: builtins.bytes = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["series", b"series"]) -> None: ...

global___RawCarryResponse = RawCarryResponse

@typing.final
class RelativeSkewDeviationRequest(google.protobuf.message.Message):
    """RelativeSkewDeviation service"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    SYMBOL_FIELD_NUMBER: builtins.int
    LOOKBACK_FIELD_NUMBER: builtins.int
    symbol: builtins.str
    lookback: builtins.int
    def __init__(
        self,
        *,
        symbol: builtins.str = ...,
        lookback: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["lookback", b"lookback", "symbol", b"symbol"]) -> None: ...

global___RelativeSkewDeviationRequest = RelativeSkewDeviationRequest

@typing.final
class RelativeSkewDeviationResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    SERIES_FIELD_NUMBER: builtins.int
    series: builtins.bytes
    def __init__(
        self,
        *,
        series: builtins.bytes = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["series", b"series"]) -> None: ...

global___RelativeSkewDeviationResponse = RelativeSkewDeviationResponse

@typing.final
class AbsoluteSkewDeviationRequest(google.protobuf.message.Message):
    """AbsoluteSkewDeviation service"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    SYMBOL_FIELD_NUMBER: builtins.int
    LOOKBACK_FIELD_NUMBER: builtins.int
    symbol: builtins.str
    lookback: builtins.int
    def __init__(
        self,
        *,
        symbol: builtins.str = ...,
        lookback: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["lookback", b"lookback", "symbol", b"symbol"]) -> None: ...

global___AbsoluteSkewDeviationRequest = AbsoluteSkewDeviationRequest

@typing.final
class AbsoluteSkewDeviationResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    SERIES_FIELD_NUMBER: builtins.int
    series: builtins.bytes
    def __init__(
        self,
        *,
        series: builtins.bytes = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["series", b"series"]) -> None: ...

global___AbsoluteSkewDeviationResponse = AbsoluteSkewDeviationResponse

@typing.final
class CumulativeDailyVolNormReturnsRequest(google.protobuf.message.Message):
    """CumulativeDailyVolNormReturns service"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    SYMBOL_FIELD_NUMBER: builtins.int
    symbol: builtins.str
    def __init__(
        self,
        *,
        symbol: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["symbol", b"symbol"]) -> None: ...

global___CumulativeDailyVolNormReturnsRequest = CumulativeDailyVolNormReturnsRequest

@typing.final
class CumulativeDailyVolNormReturnsResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    SERIES_FIELD_NUMBER: builtins.int
    series: builtins.bytes
    def __init__(
        self,
        *,
        series: builtins.bytes = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["series", b"series"]) -> None: ...

global___CumulativeDailyVolNormReturnsResponse = CumulativeDailyVolNormReturnsResponse

@typing.final
class DailyReturnsVolRequest(google.protobuf.message.Message):
    """DailyReturnsVol service"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    SYMBOL_FIELD_NUMBER: builtins.int
    symbol: builtins.str
    def __init__(
        self,
        *,
        symbol: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["symbol", b"symbol"]) -> None: ...

global___DailyReturnsVolRequest = DailyReturnsVolRequest

@typing.final
class DailyReturnsVolResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    SERIES_FIELD_NUMBER: builtins.int
    series: builtins.bytes
    def __init__(
        self,
        *,
        series: builtins.bytes = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["series", b"series"]) -> None: ...

global___DailyReturnsVolResponse = DailyReturnsVolResponse
