# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: raw_carry.proto
# Protobuf Python Version: 5.28.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    1,
    '',
    'raw_carry.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fraw_carry.proto\x12\x08raw_data\"!\n\x0fRawCarryRequest\x12\x0e\n\x06symbol\x18\x01 \x01(\t\"\"\n\x10RawCarryResponse\x12\x0e\n\x06series\x18\x01 \x01(\x0c\x32R\n\x08RawCarry\x12\x46\n\rget_raw_carry\x12\x19.raw_data.RawCarryRequest\x1a\x1a.raw_data.RawCarryResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'raw_carry_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_RAWCARRYREQUEST']._serialized_start=29
  _globals['_RAWCARRYREQUEST']._serialized_end=62
  _globals['_RAWCARRYRESPONSE']._serialized_start=64
  _globals['_RAWCARRYRESPONSE']._serialized_end=98
  _globals['_RAWCARRY']._serialized_start=100
  _globals['_RAWCARRY']._serialized_end=182
# @@protoc_insertion_point(module_scope)
