# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import rules_processor_pb2 as rules__processor__pb2

GRPC_GENERATED_VERSION = '1.68.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in rules_processor_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class RulesProcessorStub(object):
    """Centralized service
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.process_rules = channel.unary_unary(
                '/rules.RulesProcessor/process_rules',
                request_serializer=rules__processor__pb2.RulesBatchRequest.SerializeToString,
                response_deserializer=rules__processor__pb2.RulesBatchResponse.FromString,
                _registered_method=True)


class RulesProcessorServicer(object):
    """Centralized service
    """

    def process_rules(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RulesProcessorServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'process_rules': grpc.unary_unary_rpc_method_handler(
                    servicer.process_rules,
                    request_deserializer=rules__processor__pb2.RulesBatchRequest.FromString,
                    response_serializer=rules__processor__pb2.RulesBatchResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'rules.RulesProcessor', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('rules.RulesProcessor', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class RulesProcessor(object):
    """Centralized service
    """

    @staticmethod
    def process_rules(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rules.RulesProcessor/process_rules',
            rules__processor__pb2.RulesBatchRequest.SerializeToString,
            rules__processor__pb2.RulesBatchResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
