"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins
import google.protobuf.descriptor
import google.protobuf.message
import typing

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class VolAttenuationRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    SYMBOL_FIELD_NUMBER: builtins.int
    symbol: builtins.str
    def __init__(
        self,
        *,
        symbol: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["symbol", b"symbol"]) -> None: ...

global___VolAttenuationRequest = VolAttenuationRequest

@typing.final
class VolAttenuationResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    SERIES_FIELD_NUMBER: builtins.int
    series: builtins.bytes
    def __init__(
        self,
        *,
        series: builtins.bytes = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["series", b"series"]) -> None: ...

global___VolAttenuationResponse = VolAttenuationResponse
